### PR TITLE
Handle item removal consistent with PSR-16 from SimpleCacheDecorator

### LINKED ISSUE #158: PSR-16 support: prevent concurrent regression when calling delete
Per [a comment](https://github.com/zendframework/zend-cache/pull/152#issuecomment-383011006) by @marc-mabe : 

> on delete there is a concurrent regression. You first check for existence and then delete but the item could be added between both calls. As removeItem return true/false based of if the item was deleted it will throw an error only in case the deletion of an existing item failed. So probably just ignoring the return value and return true in all cases

### PR DESCRIPTION
**Pull request by weierophinney**
PSR-16 states that `delete()` and `deleteMultiple()` should return false in the case of an error, not throw an exception. This patch modifies the catch statements of each to `return false` accordingly.

Additionally, it modifies the `return $this->storage->removeItem($key)` to read `return (bool) $this->storage->removeItem($key);`. When using the `ExceptionHandler` plugin, it's possible for a `void` or `null` return value due to never receiving a result from the adapter for the operation; by casting to boolean, we ensure it properly indicates failure per the PSR-16 specification.

This patch also documents pitfalls with `delete()` and `deleteMultiple()` with regards to plugins changing the throw behavior and/or altering the result.

Finally, this patch documents which adapters require the Serializer plugin when used with PSR-16.

Alternative to #160 
Fixes #158

### CODE REVIEW

File: src/Psr/SimpleCache/SimpleCacheDecorator.php [hunk 1]
```diff
@@ -135,16 +135,12 @@ public function delete($key)
     {
         $this->validateKey($key);
 
-        if (! $this->storage->hasItem($key)) {
-            return true;
-        }
-
         try {
-            return $this->storage->removeItem($key);
+            return null !== $this->storage->removeItem($key);
```
Comment (weierophinney) [inline src/Psr/SimpleCache/SimpleCacheDecorator.php]: `null` _should_ only happen if an exception was caught, as `$result` is undefined at that point, meaning a `null` value will be returned. Boolean return values indicate that the key does not exist — `true` indicates successful removal and/or key never existed, while `false` generally only means the key wasn't present in the first place. As such, both are successful operations in terms of PSR-16, as they mean the key is not present in the storage. `null` indicates an error, which, by PSR-16, should be indicated via a `false` value.

File: src/Psr/SimpleCache/SimpleCacheDecorator.php [hunk 2]
```diff
@@ -135,16 +135,12 @@ public function delete($key)
...
         } catch (Throwable $e) {
-            throw static::translateException($e);
+            return false;
         } catch (Exception $e) {
-            throw static::translateException($e);
+            return false;
```
Comment (weierophinney) [inline src/Psr/SimpleCache/SimpleCacheDecorator.php]: PSR-16 indicates `false` should be returned from `delete()` in the event of an error. An exception is an error condition.

File: test/Psr/SimpleCache/SimpleCacheDecoratorTest.php [hunk 3]
```diff
@@ -346,32 +346,22 @@ public function testSetShouldReRaiseExceptionThrownByStorage()
...
-        $this->storage->hasItem('key')->willReturn(true);
         $this->storage->removeItem('key')->willReturn(true);
         $this->assertTrue($this->cache->delete('key'));
     }
 
     public function testDeleteShouldReturnTrueWhenItemDoesNotExist()
     {
-        $this->storage->hasItem('key')->willReturn(false);
-        $this->storage->removeItem('key')->shouldNotBeCalled();
+        $this->storage->removeItem('key')->willReturn(false);
```
Comment (weierophinney) [inline test/Psr/SimpleCache/SimpleCacheDecoratorTest.php]: This demonstrates the "`false` returned because key did not exist" scenario.

File: src/Psr/SimpleCache/SimpleCacheDecorator.php [hunk 4]
```diff
@@ -140,11 +140,11 @@ public function delete($key)
         }
 
         try {
-            return $this->storage->removeItem($key);
+            return (bool) $this->storage->removeItem($key);
```
Comment (thomasvargiu) [inline src/Psr/SimpleCache/SimpleCacheDecorator.php]: It doesn't fix #158 as a concurrent call can remove a key between `hasItem()` and `removeItem()`, resulting on returning false for a non existing key (against PSR-16 specification). Honestly I don't know what should be better.
Probably returning always `true` as @marc-mabe initially suggested could be better. Right now should be better as we are documenting it saying to don't disable exceptions. (I should read the documentation for the return value of each adapter)

File: src/Psr/SimpleCache/SimpleCacheDecorator.php [hunk 5]
```diff
@@ -257,9 +257,9 @@ public function deleteMultiple($keys)
         try {
             $result = $this->storage->removeItems($keys);
```
Comment (thomasvargiu) [inline src/Psr/SimpleCache/SimpleCacheDecorator.php]: If `delete()` should return `true` on a non set item, probably also `deleteMultiple()` should return `true` (??)

File: src/Psr/SimpleCache/SimpleCacheDecorator.php (hunk 1 above)
Comment (thomasvargiu) [reply src/Psr/SimpleCache/SimpleCacheDecorator.php]: It's perfect, it was so simple

File: src/Psr/SimpleCache/SimpleCacheDecorator.php (hunk 5 above)
Comment (thomasvargiu) [reply src/Psr/SimpleCache/SimpleCacheDecorator.php]: Can we change it with the following?

```php
return null !== $this->storage->removeItems($keys);
```

**Comment by weierophinney** [comment]
Test failure was due to a timeout. I've tried two different ways to increase it, but none of them are being honored, so at this point, we just have to restart jobs as necessary. Since only one environment timed out and all others passed, this is ready.

**Comment by thomasvargiu** [comment]
@weierophinney can we ignore composer scripts and run phpunit directly?
